<?php

namespace Database\Seeders;

use App\Models\Category;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CategorySeeder extends Seeder
{
    public function run(): void
    {
        DB::statement('SET FOREIGN_KEY_CHECKS=0;');
        Category::truncate();
        DB::statement('SET FOREIGN_KEY_CHECKS=1;');

        $categories = [
            [
                'name' => 'Hoa tươi',
                'slug' => 'hoa-tuoi',
                'icon' => 'bi bi-flower1',
                'description' => 'Danh mục hoa tươi gồm bó hoa, hộp hoa, giỏ hoa, hoa theo dịp và các loại hoa phổ biến.',
                'meta_title' => 'Hoa tươi đẹp, giao nhanh trong ngày',
                'meta_description' => 'Đặt hoa tươi đẹp tại Mộc Hương Flower Shop, nhiều mẫu hoa sinh nhật, khai trương, tình yêu và sự kiện.',
                'sort_order' => 1,
                'is_active' => true,
                'children' => [
                    [
                        'name' => 'Bó hoa',
                        'slug' => 'bo-hoa',
                        'icon' => 'bi bi-flower2',
                        'mega_section' => 'kieu_dang',
                        'sort_order' => 1,
                    ],
                    [
                        'name' => 'Hộp hoa',
                        'slug' => 'hop-hoa',
                        'icon' => 'bi bi-box-seam',
                        'mega_section' => 'kieu_dang',
                        'sort_order' => 2,
                    ],
                    [
                        'name' => 'Giỏ hoa',
                        'slug' => 'gio-hoa',
                        'icon' => 'bi bi-basket',
                        'mega_section' => 'kieu_dang',
                        'sort_order' => 3,
                    ],
                    [
                        'name' => 'Hoa để bàn',
                        'slug' => 'hoa-de-ban',
                        'icon' => 'bi bi-flower3',
                        'mega_section' => 'kieu_dang',
                        'sort_order' => 4,
                    ],
                    [
                        'name' => 'Hoa kệ đứng',
                        'slug' => 'hoa-ke-dung',
                        'icon' => 'bi bi-trophy',
                        'mega_section' => 'kieu_dang',
                        'sort_order' => 5,
                    ],
                    [
                        'name' => 'Bình hoa',
                        'slug' => 'binh-hoa',
                        'icon' => 'bi bi-cup',
                        'mega_section' => 'kieu_dang',
                        'sort_order' => 6,
                    ],

                    [
                        'name' => 'Hoa Hồng',
                        'slug' => 'hoa-hong',
                        'icon' => 'bi bi-flower1',
                        'mega_section' => 'loai_hoa',
                        'sort_order' => 1,
                    ],
                    [
                        'name' => 'Lan hồ điệp',
                        'slug' => 'lan-ho-diep',
                        'icon' => 'bi bi-flower2',
                        'mega_section' => 'loai_hoa',
                        'sort_order' => 2,
                    ],
                    [
                        'name' => 'Hướng Dương',
                        'slug' => 'huong-duong',
                        'icon' => 'bi bi-sun',
                        'mega_section' => 'loai_hoa',
                        'sort_order' => 3,
                    ],
                    [
                        'name' => 'Hoa Cúc',
                        'slug' => 'hoa-cuc',
                        'icon' => 'bi bi-flower3',
                        'mega_section' => 'loai_hoa',
                        'sort_order' => 4,
                    ],
                    [
                        'name' => 'Tulip',
                        'slug' => 'tulip',
                        'icon' => 'bi bi-flower1',
                        'mega_section' => 'loai_hoa',
                        'sort_order' => 5,
                    ],
                    [
                        'name' => 'Cẩm Chướng',
                        'slug' => 'cam-chuong',
                        'icon' => 'bi bi-flower2',
                        'mega_section' => 'loai_hoa',
                        'sort_order' => 6,
                    ],
                    [
                        'name' => 'Ly – Loa Kèn',
                        'slug' => 'ly-loa-ken',
                        'icon' => 'bi bi-flower3',
                        'mega_section' => 'loai_hoa',
                        'sort_order' => 7,
                    ],
                    [
                        'name' => 'Baby – Cát Tường',
                        'slug' => 'baby-cat-tuong',
                        'icon' => 'bi bi-stars',
                        'mega_section' => 'loai_hoa',
                        'sort_order' => 8,
                    ],

                    [
                        'name' => 'Sinh nhật',
                        'slug' => 'sinh-nhat',
                        'icon' => 'bi bi-balloon-heart',
                        'mega_section' => 'theo_dip',
                        'sort_order' => 1,
                    ],
                    [
                        'name' => 'Tình yêu / Valentine',
                        'slug' => 'tinh-yeu-valentine',
                        'icon' => 'bi bi-heart-fill',
                        'mega_section' => 'theo_dip',
                        'sort_order' => 2,
                    ],
                    [
                        'name' => 'Khai trương',
                        'slug' => 'khai-truong',
                        'icon' => 'bi bi-shop',
                        'mega_section' => 'theo_dip',
                        'sort_order' => 3,
                    ],
                    [
                        'name' => 'Tốt nghiệp',
                        'slug' => 'tot-nghiep',
                        'icon' => 'bi bi-mortarboard',
                        'mega_section' => 'theo_dip',
                        'sort_order' => 4,
                    ],
                    [
                        'name' => '8/3 · 20/10',
                        'slug' => '83-2010',
                        'icon' => 'bi bi-flower1',
                        'mega_section' => 'theo_dip',
                        'sort_order' => 5,
                    ],
                    [
                        'name' => 'Chia buồn / Tang lễ',
                        'slug' => 'chia-buon-tang-le',
                        'icon' => 'bi bi-peace',
                        'mega_section' => 'theo_dip',
                        'sort_order' => 6,
                    ],
                    [
                        'name' => 'Sự kiện công ty',
                        'slug' => 'su-kien-cong-ty',
                        'icon' => 'bi bi-building',
                        'mega_section' => 'theo_dip',
                        'sort_order' => 7,
                    ],

                    [
                        'name' => 'Hoa đỏ',
                        'slug' => 'hoa-do',
                        'icon' => 'bi bi-palette-fill',
                        'mega_section' => 'theo_mau',
                        'sort_order' => 1,
                    ],
                    [
                        'name' => 'Hoa hồng',
                        'slug' => 'hoa-hong-mau',
                        'icon' => 'bi bi-palette',
                        'mega_section' => 'theo_mau',
                        'sort_order' => 2,
                    ],
                    [
                        'name' => 'Hoa vàng',
                        'slug' => 'hoa-vang',
                        'icon' => 'bi bi-palette',
                        'mega_section' => 'theo_mau',
                        'sort_order' => 3,
                    ],
                    [
                        'name' => 'Hoa tím',
                        'slug' => 'hoa-tim',
                        'icon' => 'bi bi-palette',
                        'mega_section' => 'theo_mau',
                        'sort_order' => 4,
                    ],
                    [
                        'name' => 'Hoa trắng',
                        'slug' => 'hoa-trang',
                        'icon' => 'bi bi-palette',
                        'mega_section' => 'theo_mau',
                        'sort_order' => 5,
                    ],
                    [
                        'name' => 'Hoa cam',
                        'slug' => 'hoa-cam',
                        'icon' => 'bi bi-palette',
                        'mega_section' => 'theo_mau',
                        'sort_order' => 6,
                    ],

                    [
                        'name' => 'Hoa sáp vĩnh cửu',
                        'slug' => 'hoa-sap-vinh-cuu',
                        'icon' => 'bi bi-stars',
                        'mega_section' => 'dac_biet',
                        'sort_order' => 1,
                    ],
                    [
                        'name' => 'Hoa độc đáo',
                        'slug' => 'hoa-doc-dao',
                        'icon' => 'bi bi-magic',
                        'mega_section' => 'dac_biet',
                        'sort_order' => 2,
                    ],
                ],
            ],

            [
                'name' => 'Hoa cưới',
                'slug' => 'hoa-cuoi',
                'icon' => 'bi bi-heart-fill',
                'description' => 'Các mẫu hoa cưới, hoa cầm tay cô dâu, cổng hoa cưới và trang trí tiệc cưới.',
                'meta_title' => 'Hoa cưới đẹp, hoa cầm tay cô dâu',
                'meta_description' => 'Dịch vụ hoa cưới tại Mộc Hương Flower Shop với nhiều mẫu hoa cầm tay, cổng hoa, hoa bàn tiệc và trang trí xe hoa.',
                'sort_order' => 2,
                'is_active' => true,
                'children' => [
                    [
                        'name' => 'Hoa cầm tay cô dâu',
                        'slug' => 'hoa-cam-tay-co-dau',
                        'icon' => 'bi bi-flower1',
                        'mega_section' => 'hoa_co_dau',
                        'sort_order' => 1,
                    ],
                    [
                        'name' => 'Hoa cài áo chú rể',
                        'slug' => 'hoa-cai-ao-chu-re',
                        'icon' => 'bi bi-suit-heart',
                        'mega_section' => 'hoa_co_dau',
                        'sort_order' => 2,
                    ],
                    [
                        'name' => 'Vòng hoa đội đầu',
                        'slug' => 'vong-hoa-doi-dau',
                        'icon' => 'bi bi-flower2',
                        'mega_section' => 'phu_kien_cuoi',
                        'sort_order' => 1,
                    ],
                    [
                        'name' => 'Hoa cài tóc',
                        'slug' => 'hoa-cai-toc',
                        'icon' => 'bi bi-flower3',
                        'mega_section' => 'phu_kien_cuoi',
                        'sort_order' => 2,
                    ],
                    [
                        'name' => 'Cổng hoa cưới',
                        'slug' => 'cong-hoa-cuoi',
                        'icon' => 'bi bi-door-open',
                        'mega_section' => 'trang_tri_cuoi',
                        'sort_order' => 1,
                    ],
                    [
                        'name' => 'Trang trí xe hoa',
                        'slug' => 'trang-tri-xe-hoa',
                        'icon' => 'bi bi-car-front',
                        'mega_section' => 'trang_tri_cuoi',
                        'sort_order' => 2,
                    ],
                    [
                        'name' => 'Hoa bàn tiệc',
                        'slug' => 'hoa-ban-tiec',
                        'icon' => 'bi bi-cup-straw',
                        'mega_section' => 'trang_tri_cuoi',
                        'sort_order' => 3,
                    ],
                    [
                        'name' => 'Trang trí phòng cưới',
                        'slug' => 'trang-tri-phong-cuoi',
                        'icon' => 'bi bi-house-heart',
                        'mega_section' => 'trang_tri_cuoi',
                        'sort_order' => 4,
                    ],
                    [
                        'name' => 'Hoa backdrop chụp ảnh',
                        'slug' => 'hoa-backdrop-chup-anh',
                        'icon' => 'bi bi-camera',
                        'mega_section' => 'trang_tri_cuoi',
                        'sort_order' => 5,
                    ],
                    [
                        'name' => 'Gói cưới cơ bản',
                        'slug' => 'goi-cuoi-co-ban',
                        'icon' => 'bi bi-box',
                        'mega_section' => 'dich_vu_cuoi',
                        'sort_order' => 1,
                    ],
                    [
                        'name' => 'Gói cưới sang trọng',
                        'slug' => 'goi-cuoi-sang-trong',
                        'icon' => 'bi bi-gem',
                        'mega_section' => 'dich_vu_cuoi',
                        'sort_order' => 2,
                    ],
                    [
                        'name' => 'Tư vấn cưới miễn phí',
                        'slug' => 'tu-van-cuoi-mien-phi',
                        'icon' => 'bi bi-chat-heart',
                        'mega_section' => 'dich_vu_cuoi',
                        'sort_order' => 3,
                    ],
                ],
            ],

            [
                'name' => 'Cây & Lan',
                'slug' => 'cay-lan',
                'icon' => 'bi bi-tree',
                'description' => 'Danh mục cây xanh, cây phong thủy, lan hồ điệp và chậu cây quà tặng.',
                'meta_title' => 'Cây xanh, lan hồ điệp và chậu cây quà tặng',
                'meta_description' => 'Mua cây xanh, lan hồ điệp, cây để bàn và chậu cây quà tặng tại Mộc Hương Flower Shop.',
                'sort_order' => 3,
                'is_active' => true,
                'children' => [
                    [
                        'name' => 'Lan đơn cành',
                        'slug' => 'lan-don-canh',
                        'icon' => 'bi bi-flower1',
                        'mega_section' => 'lan',
                        'sort_order' => 1,
                    ],
                    [
                        'name' => 'Lan chậu 2–3 cành',
                        'slug' => 'lan-chau-2-3-canh',
                        'icon' => 'bi bi-flower2',
                        'mega_section' => 'lan',
                        'sort_order' => 2,
                    ],
                    [
                        'name' => 'Lan hộp quà cao cấp',
                        'slug' => 'lan-hop-qua-cao-cap',
                        'icon' => 'bi bi-gem',
                        'mega_section' => 'lan',
                        'sort_order' => 3,
                    ],
                    [
                        'name' => 'Cây để bàn văn phòng',
                        'slug' => 'cay-de-ban-van-phong',
                        'icon' => 'bi bi-pc-display-horizontal',
                        'mega_section' => 'cay_xanh',
                        'sort_order' => 1,
                    ],
                    [
                        'name' => 'Cây phong thủy',
                        'slug' => 'cay-phong-thuy',
                        'icon' => 'bi bi-stars',
                        'mega_section' => 'cay_xanh',
                        'sort_order' => 2,
                    ],
                    [
                        'name' => 'Cây treo – cây leo',
                        'slug' => 'cay-treo-cay-leo',
                        'icon' => 'bi bi-tree',
                        'mega_section' => 'cay_xanh',
                        'sort_order' => 3,
                    ],
                    [
                        'name' => 'Cây ngoài trời',
                        'slug' => 'cay-ngoai-troi',
                        'icon' => 'bi bi-brightness-high',
                        'mega_section' => 'cay_xanh',
                        'sort_order' => 4,
                    ],
                    [
                        'name' => 'Chậu cây quà tặng',
                        'slug' => 'chau-cay-qua-tang',
                        'icon' => 'bi bi-gift',
                        'mega_section' => 'qua_tang_cay',
                        'sort_order' => 1,
                    ],
                ],
            ],

            [
                'name' => 'Quà tặng',
                'slug' => 'qua-tang',
                'icon' => 'bi bi-gift-fill',
                'description' => 'Các combo quà tặng đi kèm hoa như gấu bông, chocolate, giỏ trái cây và hộp quà.',
                'meta_title' => 'Quà tặng kèm hoa đẹp và ý nghĩa',
                'meta_description' => 'Chọn quà tặng kèm hoa như gấu bông, chocolate, giỏ trái cây, hộp quà cao cấp tại Mộc Hương Flower Shop.',
                'sort_order' => 4,
                'is_active' => true,
                'children' => [
                    [
                        'name' => 'Gấu bông + hoa',
                        'slug' => 'gau-bong-hoa',
                        'icon' => 'bi bi-emoji-smile',
                        'mega_section' => 'combo_hoa',
                        'sort_order' => 1,
                    ],
                    [
                        'name' => 'Chocolate + hoa',
                        'slug' => 'chocolate-hoa',
                        'icon' => 'bi bi-box2-heart',
                        'mega_section' => 'combo_hoa',
                        'sort_order' => 2,
                    ],
                    [
                        'name' => 'Rượu vang + hoa',
                        'slug' => 'ruou-vang-hoa',
                        'icon' => 'bi bi-cup-straw',
                        'mega_section' => 'combo_hoa',
                        'sort_order' => 3,
                    ],
                    [
                        'name' => 'Mỹ phẩm + hoa',
                        'slug' => 'my-pham-hoa',
                        'icon' => 'bi bi-bag-heart',
                        'mega_section' => 'combo_hoa',
                        'sort_order' => 4,
                    ],
                    [
                        'name' => 'Giỏ quà tết',
                        'slug' => 'gio-qua-tet',
                        'icon' => 'bi bi-basket',
                        'mega_section' => 'gio_qua',
                        'sort_order' => 1,
                    ],
                    [
                        'name' => 'Giỏ trái cây tươi',
                        'slug' => 'gio-trai-cay-tuoi',
                        'icon' => 'bi bi-basket2',
                        'mega_section' => 'gio_qua',
                        'sort_order' => 2,
                    ],
                    [
                        'name' => 'Hộp quà cao cấp',
                        'slug' => 'hop-qua-cao-cap',
                        'icon' => 'bi bi-box-seam',
                        'mega_section' => 'hop_qua',
                        'sort_order' => 1,
                    ],
                    [
                        'name' => 'Set nến thơm',
                        'slug' => 'set-nen-thom',
                        'icon' => 'bi bi-fire',
                        'mega_section' => 'phu_kien',
                        'sort_order' => 1,
                    ],
                    [
                        'name' => 'Set spa – dưỡng da',
                        'slug' => 'set-spa-duong-da',
                        'icon' => 'bi bi-droplet',
                        'mega_section' => 'phu_kien',
                        'sort_order' => 2,
                    ],
                    [
                        'name' => 'Set trà – cà phê',
                        'slug' => 'set-tra-ca-phe',
                        'icon' => 'bi bi-cup-hot',
                        'mega_section' => 'phu_kien',
                        'sort_order' => 3,
                    ],
                    [
                        'name' => 'Thiệp & phong bì',
                        'slug' => 'thiep-phong-bi',
                        'icon' => 'bi bi-envelope-heart',
                        'mega_section' => 'phu_kien',
                        'sort_order' => 4,
                    ],
                ],
            ],

            [
                'name' => 'Thực phẩm',
                'slug' => 'thuc-pham',
                'icon' => 'bi bi-cake',
                'description' => 'Danh mục bánh, combo hoa bánh và thức uống dùng kèm quà tặng.',
                'meta_title' => 'Bánh sinh nhật, combo hoa bánh và thực phẩm quà tặng',
                'meta_description' => 'Mua bánh sinh nhật, bánh cưới, combo hoa bánh và nước ép trái cây tại Mộc Hương Flower Shop.',
                'sort_order' => 5,
                'is_active' => true,
                'children' => [
                    [
                        'name' => 'Bánh sinh nhật',
                        'slug' => 'banh-sinh-nhat',
                        'icon' => 'bi bi-cake2',
                        'mega_section' => 'banh',
                        'sort_order' => 1,
                    ],
                    [
                        'name' => 'Bánh hoa tươi',
                        'slug' => 'banh-hoa-tuoi',
                        'icon' => 'bi bi-flower1',
                        'mega_section' => 'banh',
                        'sort_order' => 2,
                    ],
                    [
                        'name' => 'Bánh cưới',
                        'slug' => 'banh-cuoi',
                        'icon' => 'bi bi-heart-fill',
                        'mega_section' => 'banh',
                        'sort_order' => 3,
                    ],
                    [
                        'name' => 'Bánh in ảnh',
                        'slug' => 'banh-in-anh',
                        'icon' => 'bi bi-image',
                        'mega_section' => 'banh',
                        'sort_order' => 4,
                    ],
                    [
                        'name' => 'Bánh thuần chay',
                        'slug' => 'banh-thuan-chay',
                        'icon' => 'bi bi-leaf',
                        'mega_section' => 'banh',
                        'sort_order' => 5,
                    ],
                    [
                        'name' => 'Combo hoa + bánh',
                        'slug' => 'combo-hoa-banh',
                        'icon' => 'bi bi-gift',
                        'mega_section' => 'combo',
                        'sort_order' => 1,
                    ],
                    [
                        'name' => 'Bánh trái cây tươi',
                        'slug' => 'banh-trai-cay-tuoi',
                        'icon' => 'bi bi-basket2',
                        'mega_section' => 'combo',
                        'sort_order' => 2,
                    ],
                    [
                        'name' => 'Bánh mousse – tiramisu',
                        'slug' => 'banh-mousse-tiramisu',
                        'icon' => 'bi bi-cake',
                        'mega_section' => 'combo',
                        'sort_order' => 3,
                    ],
                    [
                        'name' => 'Nước ép trái cây',
                        'slug' => 'nuoc-ep-trai-cay',
                        'icon' => 'bi bi-cup-straw',
                        'mega_section' => 'do_uong',
                        'sort_order' => 1,
                    ],
                    [
                        'name' => 'Trà hoa – trà thảo mộc',
                        'slug' => 'tra-hoa-tra-thao-moc',
                        'icon' => 'bi bi-cup-hot',
                        'mega_section' => 'do_uong',
                        'sort_order' => 2,
                    ],
                ],
            ],

            [
                'name' => 'Sự kiện',
                'slug' => 'su-kien',
                'icon' => 'bi bi-calendar-event',
                'description' => 'Dịch vụ hoa và trang trí cho sự kiện, hội nghị, khai trương và tiệc công ty.',
                'meta_title' => 'Hoa sự kiện và trang trí sự kiện',
                'meta_description' => 'Dịch vụ hoa sự kiện, trang trí hội nghị, khai trương và tiệc công ty tại Mộc Hương Flower Shop.',
                'sort_order' => 6,
                'is_active' => true,
                'children' => [
                    [
                        'name' => 'Khai trương – khánh thành',
                        'slug' => 'khai-truong-khanh-thanh',
                        'icon' => 'bi bi-shop',
                        'mega_section' => 'khac',
                        'sort_order' => 1,
                    ],
                    [
                        'name' => 'Hội nghị – hội thảo',
                        'slug' => 'hoi-nghi-hoi-thao',
                        'icon' => 'bi bi-people',
                        'mega_section' => 'khac',
                        'sort_order' => 2,
                    ],
                    [
                        'name' => 'Lễ tốt nghiệp',
                        'slug' => 'le-tot-nghiep',
                        'icon' => 'bi bi-mortarboard',
                        'mega_section' => 'khac',
                        'sort_order' => 3,
                    ],
                    [
                        'name' => 'Tiệc sinh nhật trọn gói',
                        'slug' => 'tiec-sinh-nhat-tron-goi',
                        'icon' => 'bi bi-balloon-heart',
                        'mega_section' => 'khac',
                        'sort_order' => 4,
                    ],
                    [
                        'name' => 'Trao giải – vinh danh',
                        'slug' => 'trao-giai-vinh-danh',
                        'icon' => 'bi bi-trophy',
                        'mega_section' => 'khac',
                        'sort_order' => 5,
                    ],
                    [
                        'name' => 'Nhận báo giá',
                        'slug' => 'nhan-bao-gia',
                        'icon' => 'bi bi-telephone',
                        'mega_section' => 'khac',
                        'sort_order' => 6,
                    ],
                ],
            ],

            [
                'name' => 'Đồ gỗ',
                'slug' => 'do-go',
                'icon' => 'bi bi-box-seam',
                'description' => 'Danh mục đồ gỗ dùng trong cắm hoa, trang trí hoa và trưng bày sản phẩm.',
                'meta_title' => 'Đồ gỗ cắm hoa và trang trí hoa',
                'meta_description' => 'Mua đồ gỗ cắm hoa, hộp gỗ, kệ gỗ, giỏ gỗ và phụ kiện gỗ trang trí tại Mộc Hương Flower Shop.',
                'sort_order' => 7,
                'is_active' => true,
                'children' => [
                    [
                        'name' => 'Kệ gỗ cắm hoa',
                        'slug' => 'ke-go-cam-hoa',
                        'icon' => 'bi bi-grid-3x3-gap',
                        'mega_section' => 'do_go',
                        'sort_order' => 1,
                    ],
                    [
                        'name' => 'Hộp gỗ cắm hoa',
                        'slug' => 'hop-go-cam-hoa',
                        'icon' => 'bi bi-box-seam',
                        'mega_section' => 'do_go',
                        'sort_order' => 2,
                    ],
                    [
                        'name' => 'Giỏ gỗ',
                        'slug' => 'gio-go',
                        'icon' => 'bi bi-basket',
                        'mega_section' => 'do_go',
                        'sort_order' => 3,
                    ],
                    [
                        'name' => 'Khay gỗ trang trí',
                        'slug' => 'khay-go-trang-tri',
                        'icon' => 'bi bi-layout-three-columns',
                        'mega_section' => 'do_go',
                        'sort_order' => 4,
                    ],
                    [
                        'name' => 'Thùng gỗ cắm hoa',
                        'slug' => 'thung-go-cam-hoa',
                        'icon' => 'bi bi-archive',
                        'mega_section' => 'do_go',
                        'sort_order' => 5,
                    ],
                    [
                        'name' => 'Đế gỗ trang trí',
                        'slug' => 'de-go-trang-tri',
                        'icon' => 'bi bi-square',
                        'mega_section' => 'do_go',
                        'sort_order' => 6,
                    ],
                ],
            ],

            [
                'name' => 'Phụ kiện',
                'slug' => 'phu-kien',
                'icon' => 'bi bi-tools',
                'description' => 'Danh mục phụ kiện ngành hoa gồm nước dưỡng hoa, sơn xịt hoa, ruy băng, giấy gói, xốp cắm hoa và vật tư trang trí.',
                'meta_title' => 'Phụ kiện hoa, nước dưỡng hoa, ruy băng, giấy gói',
                'meta_description' => 'Mua phụ kiện hoa, nước dưỡng hoa, sơn xịt hoa, ruy băng, giấy gói, xốp cắm hoa và vật tư trang trí tại Mộc Hương Flower Shop.',
                'sort_order' => 8,
                'is_active' => true,
                'children' => [
                    [
                        'name' => 'Nước dưỡng hoa',
                        'slug' => 'nuoc-duong-hoa',
                        'icon' => 'bi bi-droplet',
                        'mega_section' => 'vat_tu_hoa',
                        'sort_order' => 1,
                    ],
                    [
                        'name' => 'Sơn xịt hoa',
                        'slug' => 'son-xit-hoa',
                        'icon' => 'bi bi-paint-bucket',
                        'mega_section' => 'vat_tu_hoa',
                        'sort_order' => 2,
                    ],
                    [
                        'name' => 'Ruy băng',
                        'slug' => 'ruy-bang',
                        'icon' => 'bi bi-bookmark-heart',
                        'mega_section' => 'goi_hoa',
                        'sort_order' => 1,
                    ],
                    [
                        'name' => 'Giấy gói hoa',
                        'slug' => 'giay-goi-hoa',
                        'icon' => 'bi bi-file-earmark',
                        'mega_section' => 'goi_hoa',
                        'sort_order' => 2,
                    ],
                    [
                        'name' => 'Xốp cắm hoa',
                        'slug' => 'xop-cam-hoa',
                        'icon' => 'bi bi-bricks',
                        'mega_section' => 'vat_tu_hoa',
                        'sort_order' => 3,
                    ],
                    [
                        'name' => 'Dây kẽm & băng keo hoa',
                        'slug' => 'day-kem-bang-keo-hoa',
                        'icon' => 'bi bi-tools',
                        'mega_section' => 'vat_tu_hoa',
                        'sort_order' => 4,
                    ],
                    [
                        'name' => 'Lưới gói hoa',
                        'slug' => 'luoi-goi-hoa',
                        'icon' => 'bi bi-grid',
                        'mega_section' => 'goi_hoa',
                        'sort_order' => 3,
                    ],
                    [
                        'name' => 'Túi đựng hoa',
                        'slug' => 'tui-dung-hoa',
                        'icon' => 'bi bi-bag-heart',
                        'mega_section' => 'goi_hoa',
                        'sort_order' => 4,
                    ],
                    [
                        'name' => 'Thiệp chúc mừng',
                        'slug' => 'thiep-chuc-mung',
                        'icon' => 'bi bi-envelope-heart',
                        'mega_section' => 'trang_tri',
                        'sort_order' => 1,
                    ],
                    [
                        'name' => 'Phụ kiện trang trí',
                        'slug' => 'phu-kien-trang-tri',
                        'icon' => 'bi bi-stars',
                        'mega_section' => 'trang_tri',
                        'sort_order' => 2,
                    ],
                ],
            ],

            [
                'name' => 'Dịch vụ',
                'slug' => 'dich-vu',
                'icon' => 'bi bi-gear',
                'description' => 'Các dịch vụ đặt hoa, giao hoa, tư vấn mẫu hoa và thiết kế hoa theo yêu cầu.',
                'meta_title' => 'Dịch vụ hoa tươi Mộc Hương',
                'meta_description' => 'Dịch vụ đặt hoa, giao hoa, tư vấn và thiết kế hoa theo yêu cầu tại Mộc Hương Flower Shop.',
                'sort_order' => 9,
                'is_active' => true,
                'children' => [
                    [
                        'name' => 'Giao hoa nhanh 2h',
                        'slug' => 'giao-hoa-nhanh-2h',
                        'icon' => 'bi bi-truck',
                        'mega_section' => 'khac',
                        'sort_order' => 1,
                    ],
                    [
                        'name' => 'Đặt hoa định kỳ',
                        'slug' => 'dat-hoa-dinh-ky',
                        'icon' => 'bi bi-calendar-check',
                        'mega_section' => 'khac',
                        'sort_order' => 2,
                    ],
                    [
                        'name' => 'Thiết kế theo yêu cầu',
                        'slug' => 'thiet-ke-theo-yeu-cau',
                        'icon' => 'bi bi-brush',
                        'mega_section' => 'khac',
                        'sort_order' => 3,
                    ],
                    [
                        'name' => 'Trang trí không gian',
                        'slug' => 'trang-tri-khong-gian',
                        'icon' => 'bi bi-house-heart',
                        'mega_section' => 'khac',
                        'sort_order' => 4,
                    ],
                    [
                        'name' => 'Hợp tác doanh nghiệp B2B',
                        'slug' => 'hop-tac-doanh-nghiep-b2b',
                        'icon' => 'bi bi-building',
                        'mega_section' => 'khac',
                        'sort_order' => 5,
                    ],
                    [
                        'name' => 'Cho thuê hoa – phụ kiện',
                        'slug' => 'cho-thue-hoa-phu-kien',
                        'icon' => 'bi bi-camera',
                        'mega_section' => 'khac',
                        'sort_order' => 6,
                    ],
                ],
            ],
        ];

        foreach ($categories as $catData) {
            $parent = Category::create([
                'name' => $catData['name'],
                'slug' => $catData['slug'],
                'parent_id' => null,
                'mega_section' => null,
                'icon' => $catData['icon'] ?? null,
                'description' => $catData['description'] ?? null,
                'meta_title' => $catData['meta_title'] ?? null,
                'meta_description' => $catData['meta_description'] ?? null,
                'sort_order' => $catData['sort_order'] ?? 0,
                'is_active' => $catData['is_active'] ?? true,
            ]);

            foreach ($catData['children'] ?? [] as $child) {
                Category::create([
                    'name' => $child['name'],
                    'slug' => $child['slug'],
                    'parent_id' => $parent->id,
                    'mega_section' => $child['mega_section'] ?? null,
                    'icon' => $child['icon'] ?? null,
                    'description' => $child['description'] ?? null,
                    'meta_title' => $child['meta_title'] ?? $child['name'] . ' - Mộc Hương Flower Shop',
                    'meta_description' => $child['meta_description'] ?? 'Khám phá danh mục ' . $child['name'] . ' tại Mộc Hương Flower Shop.',
                    'sort_order' => $child['sort_order'] ?? 0,
                    'is_active' => $child['is_active'] ?? true,
                ]);
            }
        }

        $this->command->info('CategorySeeder chạy thành công!');
    }
}